import type { Metadata } from "next";
import { Finger_Paint, Inter } from "next/font/google";
import "./globals.css";

const finger = Finger_Paint({
  weight: "400",
  variable: "--font-finger",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: ["favicon.ico"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={finger.className}>{children}</body>
    </html>
  );
}
